/**
 * PetrolStationBackend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FuelTypesDTO = 0 | 1 | 2 | 3 | 4 | 5;

export const FuelTypesDTO = {
    NUMBER_0: 0 as FuelTypesDTO,
    NUMBER_1: 1 as FuelTypesDTO,
    NUMBER_2: 2 as FuelTypesDTO,
    NUMBER_3: 3 as FuelTypesDTO,
    NUMBER_4: 4 as FuelTypesDTO,
    NUMBER_5: 5 as FuelTypesDTO
};