/**
 * PetrolStationBackend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FuelTypesDTO } from './fuelTypesDTO';

export interface StatusDTO { 
    id?: number;
    petrolStationId?: number;
    fuelType?: FuelTypesDTO;
    createdAt?: Date;
    createdBy?: string;
    isThereFuel?: boolean;
}